import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/Header";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  fallback: ["sans-serif"],
});

const rootFonts = `
:root {
--font-poppins: ${poppins.style.fontFamily};
}
`;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <style>{rootFonts}</style>
        <Header />
        {children}
      </body>
    </html>
  );
}
